### ISSUE TITLE
Git workflow review

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#54]
- [ ] Выяснить что это такое
- [ ] Написать, предоставить @leiluk1 для репорта

**Comment by SnejUgal** [comment]
единственная проблема — весь бэк на прошлой неделе пилился в двух ветках. а так наш git workflow идеален

**Comment by fedor-ivn** [comment]
> единственная проблема — весь бэк на прошлой неделе пилился в двух ветках. а так наш git workflow норм

ну хз, мне кажется такой ответ не устроит нашего ТА...
