### ISSUE TITLE
Assignment 5: Frontend

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#78]
- [x] **Select testing frameworks, linters, etc. and justify why we selected them**
    Testing: [`jest`](https://jestjs.io/), because it integrates with React very well
    Linter: [`eslint`](https://eslint.org/), because it is _de facto_ the standard linter in the JS ecosystem
    Formatter: [`prettier`](https://prettier.io/), because it is _de facto_ the standard formatter in the JS ecosystem

 - [x] **Write unit tests**

Extra points will be awarded for additional, justified tools 🤡 and for 100% test coverage 🤡🤡

**Comment by fedor-ivn** [comment]
@SnejUgal I propose adding links to the tools

**Comment by SnejUgal** [comment]
> @SnejUgal I propose adding links to the tools

done
