### ISSUE TITLE
Assignment 5: Backlog

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#81]
- [x] **Write ACs for 5 already-implemented User Stories**
    Although we already have ACs for User Stories, they use a different format. Most probably, we need to rephrase them so as they fit the “Given ..., when ..., then ...” format

**Comment by fedor-ivn** [comment]
> ... already have _User Storie_

Don't you mean AC ?

**Comment by SnejUgal** [comment]
> Don't you mean AC ?

fixed

**Comment by RuslanKudinov** [comment]
https://github.com/InnoSWP/b21-02-anonymous-feedback/issues/1
