### ISSUE TITLE
Sharing feedback sessions

### ISSUE THREAD

**Issue by eivankin** [InnoSWP/b21-02-anonymous-feedback#9]
As an instructor I want to share my feedback sessions with students so they can easily join them.

## AC-01
Instructor shares his/her feedback session with students.
1. Instructor clicks the button `Copy join link`.
2. Instructor sends link to the students in telegram chat.
3. Students join feedback session using link sent by the instructor.

**Comment by SnejUgal** [comment]
Sharing _per se_ now works. Although we will likely change how it's implemented, that will be tracked in other issues. For this reason, I'm going to close this issue.
