### ISSUE TITLE
Assignment 6: license

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#96]
- [x] Add the MIT license to your repository and Readme
- [x] Write a brief explanation about the MIT license:
    - what it is;
    - how it differs from other open-source licenses.

    **The explanation should at least three sentences long!**

**Comment by fedor-ivn** [comment]
The MIT license is a free and open-source license that only requires the maintenance of copyright and licensing statements. Larger works, modified works, and licensed works may all be distributed with different terms and without the original source code.

Permissions
- Commercial use
- Distribution
- Modification
- Private use
Conditions
- License and copyright notice
Limitations
- Liability
- Warranty
